export const BOOK_SEARCH_REQUEST = 'BOOK_SEARCH_REQUEST';
export const BOOK_SEARCH_SUCCESS = 'BOOK_SEARCH_SUCCESS';
export const BOOK_SEARCH_FAILURE = 'BOOK_SEARCH_FAILURE';

export const BOOK_DETAIL_REQUEST = 'BOOK_DETAIL_REQUEST';
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS';
export const BOOK_DETAIL_FAILURE = 'BOOK_DETAIL_FAILURE';

export const AUTHOR_DETAIL_REQUEST = 'AUTHOR_DETAIL_REQUEST';
export const AUTHOR_DETAIL_SUCCESS = 'AUTHOR_DETAIL_SUCCESS';
export const AUTHOR_DETAIL_FAILURE = 'AUTHOR_DETAIL_FAILURE';
